/* ============================================================
   COURIER APP · screens
   ============================================================ */
const { useState } = React;

/* ----------------------------------------------------------------
   LOGIN
---------------------------------------------------------------- */
function LoginScreen({ onLogin }) {
  const [mode, setMode] = useState("qr");
  const [phone, setPhone] = useState("");
  const [pw, setPw] = useState("");
  return (
    <div className="login">
      <div className="login__top">
        <div className="login__logo">A</div>
        <div className="login__brand">Alpha<span>POS</span></div>
        <div className="login__tag">Courier · {CDB.courier.branch}</div>
      </div>
      <div className="login__sheet">
        <div className="seg" style={{ marginBottom: 20 }}>
          <button className={"seg__btn" + (mode === "qr" ? " is-active" : "")} onClick={() => setMode("qr")}>
            <Icon name="qr" size={17} /> Scan QR
          </button>
          <button className={"seg__btn" + (mode === "phone" ? " is-active" : "")} onClick={() => setMode("phone")}>
            <Icon name="phone" size={16} /> Phone
          </button>
        </div>

        {mode === "qr" ? (
          <div className="ca-stack ca-stack--lg">
            <div className="qrframe">
              <span className="qrframe__corner tl"></span>
              <span className="qrframe__corner tr"></span>
              <span className="qrframe__corner bl"></span>
              <span className="qrframe__corner br"></span>
              <div className="qrframe__scan"></div>
              <Icon name="qr" size={68} style={{ color: "rgba(255,255,255,0.22)" }} />
              <div className="qrframe__hint">Point the camera at your staff QR code</div>
            </div>
            <button className="btn btn--primary" onClick={onLogin}>
              <Icon name="scan" size={20} /> I scanned the code
            </button>
            <div style={{ textAlign: "center", fontSize: "var(--fs-sm)", color: "var(--text-tertiary)" }}>
              QR is generated by your manager in the admin panel.
            </div>
          </div>
        ) : (
          <div className="ca-stack ca-stack--lg">
            <div className="field">
              <label className="field__label">Phone number</label>
              <div className="control">
                <span className="control__prefix">+998</span>
                <input inputMode="numeric" placeholder="90 123 45 67"
                       value={phone} onChange={(e) => setPhone(e.target.value)} />
              </div>
            </div>
            <div className="field">
              <label className="field__label">Password</label>
              <div className="control">
                <Icon name="lock" size={18} />
                <input type="password" placeholder="••••••••"
                       value={pw} onChange={(e) => setPw(e.target.value)} />
              </div>
            </div>
            <button className="btn btn--primary" onClick={onLogin}>
              <Icon name="arrowright" size={20} /> Log in
            </button>
            <div style={{ textAlign: "center", fontSize: "var(--fs-sm)", color: "var(--text-tertiary)" }}>
              No account? Ask your manager to register you.
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

/* ----------------------------------------------------------------
   ORDERS (home)
---------------------------------------------------------------- */
function OrdersScreen({ online, setOnline, onOpen, onBell, onBalance, unread }) {
  const [tab, setTab] = useState("active");
  const c = CDB.courier;
  const list = tab === "active" ? CDB.active : CDB.completed;

  return (
    <React.Fragment>
      <div className="ca-head">
        <div className="ca-head__row">
          <button className="iconbtn" onClick={() => onOpen.profile()} style={{ padding: 0, border: "none", background: "none" }}>
            <div className="avatar">{c.initials}</div>
          </button>
          <div>
            <div className="ca-head__hello">Welcome back</div>
            <div className="ca-head__name">{c.first} {c.last}</div>
          </div>
          <div className="ca-head__spacer"></div>
          <div className="iconbtn" onClick={onBell}>
            <Icon name="bell" size={20} />
            {unread > 0 && <span className="iconbtn__dot"></span>}
          </div>
        </div>
        <div style={{ display: "flex", gap: "var(--sp-3)", marginTop: "var(--sp-5)" }}>
          <div className={"shift-toggle" + (online ? " is-on" : "")} style={{ flex: 1 }}
               onClick={() => setOnline(!online)}>
            <span className="shift-toggle__dot"></span>
            <span className="shift-toggle__label">{online ? "On shift · available" : "Off shift"}</span>
            <span className="ca-head__spacer"></span>
            <span className={"switch" + (online ? " is-on" : "")}></span>
          </div>
        </div>
      </div>

      <PullToRefresh skeleton={
        <div className="ca-pad ca-pad--tab ca-stack">
          <SkeletonOrderCard /><SkeletonOrderCard /><SkeletonOrderCard />
        </div>
      }>
        <div className="ca-pad ca-pad--tab ca-stack ca-stack--lg">
          <button className="balance-pill" onClick={onBalance}>
            <div className="balance-pill__icon"><Icon name="banknote" size={20} /></div>
            <div style={{ flex: 1, minWidth: 0 }}>
              <div className="balance-pill__label">Cash to hand in</div>
              {CDB.heldTotal > 0 ? (
                <React.Fragment>
                  <div className="balance-pill__value">{fmt.money(CDB.heldTotal)} <span style={{ fontSize: 13, fontWeight: 500, opacity: .55 }}>so'm</span></div>
                  <div className="balance-pill__cap">Collected from clients · give to the cashier</div>
                </React.Fragment>
              ) : (
                <div className="balance-pill__value" style={{ color: "#7BE0A8" }}>All clear</div>
              )}
            </div>
            <span className="balance-pill__chev"><Icon name="chevright" size={20} /></span>
          </button>

          <div className="qstats">
            <div className="qstat"><div className="qstat__v mono"><Odometer value={CDB.stats.deliveries} format={(n)=>String(Math.round(n))} delay={0} /></div><div className="qstat__l">Deliveries</div></div>
            <div className="qstat"><div className="qstat__v mono"><Odometer value={CDB.stats.earnings} delay={80} /></div><div className="qstat__l">Earned</div></div>
            <div className="qstat"><div className="qstat__v mono"><Odometer value={CDB.stats.avgMinutes} format={(n)=>String(Math.round(n))} delay={160} /><small style={{ fontSize: 12 }}>m</small></div><div className="qstat__l">Avg time</div></div>
          </div>

          <div className="goal-row">
            <div className="goal-row__top">
              <span className="goal-row__l">Daily goal</span>
              <span className="goal-row__v mono">{CDB.stats.deliveries}/12</span>
            </div>
            <GoalBar value={CDB.stats.deliveries} max={12} />
          </div>

          <div className="seg">
            <button className={"seg__btn" + (tab === "active" ? " is-active" : "")} onClick={() => setTab("active")}>
              Active <span className="seg__count">{CDB.active.length}</span>
            </button>
            <button className={"seg__btn" + (tab === "completed" ? " is-active" : "")} onClick={() => setTab("completed")}>
              Completed <span className="seg__count">{CDB.completed.length}</span>
            </button>
          </div>

          <div className="ca-stack">
            {tab === "active"
              ? list.map((o) => <ActiveOrderCard key={o.id} order={o} onOpen={() => onOpen.detail(o)} />)
              : list.map((o) => <CompletedOrderCard key={o.id} order={o} />)}
          </div>
        </div>
      </PullToRefresh>
    </React.Fragment>
  );
}

function ActiveOrderCard({ order, onOpen }) {
  const b = stepBadge(order.step);
  const live = order.step === "ON_WAY" || order.step === "READY";
  return (
    <div className={"ocard" + (live ? " is-live" : "")} onClick={onOpen}>
      <div className="ocard__top">
        <span className="ocard__id">#{order.id}</span>
        <Badge tone={b.tone} dot={b.dot}>{b.label}</Badge>
        <span className="ocard__time">{order.placedAt}</span>
      </div>
      <div className="ocard__body">
        <div className="ocard__addr">
          <Icon name="pin" size={16} />
          <div><b>{order.customer.name}</b> · {order.address.text}</div>
        </div>
        <div className="ocard__foot">
          <span className="ocard__total mono">{fmt.money(order.total)}</span>
          {order.payment === "UNPAID"
            ? <Badge tone="warning" dot={false}>Collect cash</Badge>
            : <Badge tone="success" dot={false}>Paid</Badge>}
          <span className="ocard__fee">+{fmt.money(order.fee)}</span>
        </div>
      </div>
    </div>
  );
}

function CompletedOrderCard({ order }) {
  return (
    <div className="ocard" style={{ cursor: "default" }}>
      <div className="ocard__top">
        <span className="ocard__id">#{order.id}</span>
        <Badge tone="neutral" dot={false}>Delivered</Badge>
        <span className="ocard__time">{order.deliveredAt}</span>
      </div>
      <div className="ocard__body">
        <div className="ocard__addr">
          <Icon name="checkcircle" size={16} style={{ color: "var(--success)" }} />
          <div><b>{order.customer.name}</b> · {order.area} · {order.minutes} min</div>
        </div>
        <div className="ocard__foot">
          <span className="ocard__total mono">{fmt.money(order.total)}</span>
          <Badge tone="success" dot={false}>Paid</Badge>
          <span className="ocard__fee">+{fmt.money(order.fee)}</span>
        </div>
      </div>
    </div>
  );
}

/* ----------------------------------------------------------------
   ORDER DETAIL
---------------------------------------------------------------- */
function OrderDetail({ order, addressMode, T, qrResult, onBack, onPush, onPaid }) {
  const [step, setStep] = useState(order.step);
  const [sheet, setSheet] = useState(false);
  const [pay, setPay] = useState(order.payment);
  const [flow, setFlow] = useState(null);        // collect | cash | split | qr | qr-split
  const [paidMethod, setPaidMethod] = useState(null);
  const [splitCash, setSplitCash] = useState(0);
  const [refunded, setRefunded] = useState(false);
  const [celebrate, setCelebrate] = useState(false);
  const tr = T || ((k) => k);
  function handlePaid(method) {
    setPay("PAID"); setPaidMethod(method); setFlow(null); setRefunded(false);
    if (onPaid) onPaid(order, method);
  }
  const b = stepBadge(step);
  const act = nextAction(step);
  const hasCoords = order.address.coords && addressMode !== "text";
  const sharing = step === "PICKED_UP" || step === "ON_WAY";
  const idx = CDB.STEPS.indexOf(step);

  function advance() {
    if (!act.next) return;
    setStep(act.next);
    if (act.next === "DELIVERED") {
      setCelebrate(true);
      setTimeout(() => setCelebrate(false), 1300);
    }
  }

  return (
    <React.Fragment>
      <div className="det-head">
        <div className="iconbtn" onClick={onBack}><Icon name="chevleft" size={22} /></div>
        <div>
          <div className="det-head__title">Order #{order.id}</div>
          <div className="det-head__sub">Placed {order.placedAt} · {order.address.distanceKm} km away</div>
        </div>
        <span className="ca-head__spacer"></span>
        <Badge key={step} tone={b.tone} dot={b.dot} className="is-morph">{b.label}</Badge>
      </div>

      <div className="ca-scroll">
        <div className="ca-pad ca-stack ca-stack--lg" style={{ paddingBottom: 24 }}>

          {/* timeline */}
          <div className="card card__pad">
            <div className="timeline">
              {CDB.STEPS.map((s, i) => {
                const state = i < idx ? "is-done" : i === idx ? "is-current" : "";
                const sub = s === "ASSIGNED" ? order.etaReady
                  : (i === idx ? "In progress now" : (i < idx ? "Done" : ""));
                return (
                  <div className={"tl-step " + state} key={s}>
                    <div className="tl-step__rail">
                      <div className="tl-step__dot">{i <= idx && <Icon name="check" size={13} weight={2.6} />}</div>
                      {i < CDB.STEPS.length - 1 && <div className="tl-step__line"></div>}
                    </div>
                    <div className="tl-step__body">
                      <div className="tl-step__t">{CDB.STEP_LABEL[s]}</div>
                      {sub && <div className="tl-step__s">{sub}</div>}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {sharing && (
            <div style={{ display: "flex", justifyContent: "center" }}>
              <span className="share-pill"><span className="share-pill__live"></span> Sharing live location with cashier</span>
            </div>
          )}

          {/* location */}
          <div>
            <div className="ca-sectlabel"><Icon name="pin" size={13} /> Delivery location</div>
            <div className="mapcard">
              {hasCoords && <MapView order={order} />}
              <div className="addr-row">
                <Icon name="pin" size={20} />
                <div style={{ flex: 1 }}>
                  <div className="addr-row__main">{order.address.text}</div>
                  {order.address.landmark && <div className="addr-row__sub">{order.address.landmark}</div>}
                  {!hasCoords && <div className="addr-row__sub" style={{ marginTop: 6, color: "var(--text-tertiary)" }}>
                    <Icon name="info" size={13} style={{ verticalAlign: "-2px", marginRight: 4 }} />
                    Text address only — no map pin shared</div>}
                </div>
              </div>
              <div className="divider"></div>
              <div style={{ padding: "var(--sp-3) var(--sp-4)", display: "flex", gap: "var(--sp-3)" }}>
                <button className="btn btn--primary btn--sm" onClick={() => setSheet(true)}>
                  <Icon name="navigation" size={18} /> {hasCoords ? "Open route" : "Search address"}
                </button>
              </div>
            </div>
          </div>

          {/* customer */}
          <div>
            <div className="ca-sectlabel"><Icon name="user" size={13} /> Customer</div>
            <div className="card">
              <div className="lrow">
                <div className="lrow__icon t-primary"><Icon name="user" size={20} /></div>
                <div className="lrow__main">
                  <div className="lrow__t">{order.customer.name}</div>
                  <div className="lrow__s mono">{order.customer.phone}</div>
                </div>
                <a className="lrow__call" href={"tel:" + order.customer.phone.replace(/\s/g, "")}>
                  <Icon name="phone" size={20} />
                </a>
              </div>
            </div>
          </div>

          {/* payment / collect */}
          <div>
            <div className="ca-sectlabel"><Icon name="banknote" size={13} /> {tr("collect_payment")}</div>
            <div className={"collect" + (pay === "PAID" ? " is-paid" : "")}>
              <div className="collect__icon"><Icon name={pay === "PAID" ? "checkcircle" : "banknote"} size={24} /></div>
              <div style={{ flex: 1 }}>
                <div className="collect__l">{pay === "PAID" ? (paidMethod ? tr("payment_received") : tr("paid_online_full")) : tr("collect_cash_full")}</div>
                <div className="collect__v mono">{fmt.moneySom(order.total)}</div>
              </div>
              {pay === "PAID" && <span className="badge t-success" style={{ alignSelf: "center" }}><Icon name="check" size={12} /> {tr("paid")}</span>}
            </div>

            {pay === "PAID" && paidMethod && (
              <div style={{ display: "flex", alignItems: "center", gap: 6, marginTop: 8, fontSize: "var(--fs-sm)", color: "var(--text-secondary)" }}>
                <Icon name="receipt" size={14} style={{ color: "var(--text-tertiary)" }} />
                <span>{tr("fiscal_receipt")}</span>
                <span className="ca-head__spacer"></span>
                <button onClick={() => { setPay("UNPAID"); setPaidMethod(null); setRefunded(true); }}
                        style={{ background: "none", border: "none", color: "var(--error)", fontWeight: 600, fontSize: "var(--fs-sm)", cursor: "pointer", fontFamily: "inherit", display: "inline-flex", alignItems: "center", gap: 4 }}>
                  <Icon name="refresh" size={13} /> {tr("refund")}
                </button>
              </div>
            )}
            {refunded && pay !== "PAID" && (
              <div className="badge t-error" style={{ marginTop: 8 }}><Icon name="refresh" size={11} /> {tr("refunded")}</div>
            )}

            {pay === "UNPAID" && (
              <React.Fragment>
                <div style={{ fontSize: "var(--fs-sm)", color: "var(--text-tertiary)", margin: "8px 0 12px", display: "flex", gap: 6 }}>
                  <Icon name="info" size={14} style={{ flex: "0 0 14px", marginTop: 2 }} />
                  <span>{tr("held_note", { v: fmt.money(order.total) })}</span>
                </div>
                <button className="btn btn--primary" onClick={() => setFlow("collect")}>
                  <Icon name="wallet" size={20} /> {tr("collect_payment")}
                </button>
              </React.Fragment>
            )}
          </div>

          {/* items */}
          <div>
            <div className="ca-sectlabel"><Icon name="receipt" size={13} /> Items <span className="ca-sectlabel__count">· {order.lines.length}</span></div>
            <div className="card">
              {order.lines.map((l, i) => (
                <div className="iline" key={i}>
                  <span className="iline__qty">{l.qty}×</span>
                  <span className="iline__name">{l.name}</span>
                  <span className="iline__price">{fmt.money(l.price)}</span>
                </div>
              ))}
              <div className="divider"></div>
              <div className="iline iline--total">
                <span className="iline__name">Total</span>
                <span className="ca-head__spacer"></span>
                <span className="iline__price mono">{fmt.moneySom(order.total)}</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="det-foot">
        {celebrate && <div className="floatup" style={{ bottom: 86 }}>+{fmt.money(order.fee)} so'm</div>}
        <button className={"btn btn--" + act.variant} disabled={act.disabled} onClick={advance}>
          <Icon name={act.icon} size={20} /> {act.label}
        </button>
        {step === "ASSIGNED" && (
          <div className="det-foot__hint">
            <Icon name="bell" size={13} /> You'll get a push when the kitchen marks it ready
          </div>
        )}
        {step === "DELIVERED" && (
          <div className="det-foot__hint"><Icon name="checkcircle" size={13} /> Delivery complete · fee +{fmt.money(order.fee)}</div>
        )}
      </div>

      {celebrate && (
        <div className="celebrate">
          <div className="celebrate__inner">
            <div className="ripple"></div>
            <DrawCheck size={88} stroke="var(--success)" pop />
            <div className="celebrate__cap">{b.label}</div>
          </div>
        </div>
      )}

      {sheet && <NavSheet order={order} onClose={() => setSheet(false)} />}

      {flow === "collect" && (
        <CollectSheet order={order} T={tr} onClose={() => setFlow(null)}
          onPick={(m) => setFlow(m === "qr" ? "qr" : m === "cash" ? "cash" : "split")} />
      )}
      {flow === "cash" && (
        <CashSheet order={order} T={tr} onClose={() => setFlow(null)} onConfirm={() => handlePaid("cash")} />
      )}
      {flow === "split" && (
        <SplitSheet order={order} T={tr} onClose={() => setFlow(null)}
          onContinueQR={(cash) => { setSplitCash(cash); setFlow("qr-split"); }} />
      )}
      {flow === "qr" && (
        <QRPayScreen order={order} amount={order.total} T={tr} qrResult={qrResult}
          onBack={() => setFlow(null)} onPaid={(m) => handlePaid(m)} />
      )}
      {flow === "qr-split" && (
        <QRPayScreen order={order} amount={order.total - splitCash} splitCash={splitCash} T={tr} qrResult={qrResult}
          onBack={() => setFlow("split")} onPaid={() => handlePaid("split")} />
      )}
    </React.Fragment>
  );
}

/* ----------------------------------------------------------------
   TODAY (stats)
---------------------------------------------------------------- */
function TodayScreen() {
  const s = CDB.stats;
  const maxN = Math.max.apply(null, s.byHour.map((x) => x.n)) || 1;
  const tiles = [
    { l: "Deliveries", num: s.deliveries, fmt: (n) => String(Math.round(n)), icon: "checkcircle", tone: "success" },
    { l: "Earned", num: s.earnings, unit: "so'm", icon: "wallet", tone: "primary" },
    { l: "Cash collected", num: s.cashCollected, unit: "so'm", icon: "banknote", tone: "warning" },
    { l: "Avg delivery", num: s.avgMinutes, unit: "min", fmt: (n) => String(Math.round(n)), icon: "clock", tone: "info" },
    { l: "Active time", text: s.activeHours, icon: "history", tone: "neutral" },
    { l: "Distance", num: s.distanceKm, unit: "km", fmt: (n) => String(Math.round(n)), icon: "navigation", tone: "primary" },
  ];
  return (
    <React.Fragment>
      <div className="ca-head"><div className="ca-head__row"><h1 className="ca-head__title">Today</h1>
        <span className="ca-head__spacer"></span>
        <span className="badge t-neutral badge--dot">{CDB.courier.branch}</span></div>
      </div>
      <div className="ca-scroll">
        <div className="ca-pad ca-pad--tab ca-stack ca-stack--lg">
          <div className="kgrid">
            {tiles.map((t, i) => (
              <div className="ktile" key={i}>
                <div className="ktile__top">
                  <div className={"ktile__icon t-" + t.tone}><Icon name={t.icon} size={18} /></div>
                  <div className="ktile__l">{t.l}</div>
                </div>
                <div className="ktile__v">
                  {t.text != null ? t.text : <CountUp value={t.num} format={t.fmt} duration={900} />}
                  {t.unit && <small> {t.unit}</small>}
                </div>
              </div>
            ))}
          </div>

          <div className="card">
            <div className="card__hd"><Icon name="chart" size={15} /><span className="card__hd-title">Deliveries by hour</span></div>
            <div className="card__pad" style={{ paddingTop: 0 }}>
              <div className="bars">
                {s.byHour.map((x, i) => (
                  <div className="bars__col" key={i}>
                    <div className={"bars__bar" + (x.n === 0 ? " is-zero" : "")} style={{ height: (x.n / maxN * 100) + "%" }}></div>
                    <div className="bars__h">{x.h}</div>
                  </div>
                ))}
              </div>
            </div>
          </div>

          <div>
            <div className="ca-sectlabel">Completed today <span className="ca-sectlabel__count">· {CDB.completed.length}</span></div>
            <div className="ca-stack">
              {CDB.completed.map((o) => <CompletedOrderCard key={o.id} order={o} />)}
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

/* ----------------------------------------------------------------
   BALANCE
---------------------------------------------------------------- */
function BalanceScreen() {
  return (
    <React.Fragment>
      <div className="ca-head"><div className="ca-head__row"><h1 className="ca-head__title">Balance</h1></div></div>
      <div className="ca-scroll">
        <div className="ca-pad ca-pad--tab ca-stack ca-stack--lg">
          <div className="bal-hero">
            <div className="bal-hero__l">Current balance</div>
            <div className={"bal-hero__v" + (CDB.balance < 0 ? " is-neg" : "")}>{fmt.signed(CDB.balance)}</div>
            <div className="bal-hero__note">
              <Icon name="info" size={15} />
              <span>Unpaid orders you're carrying are held against your balance. It clears when the cashier marks them paid or cancelled.</span>
            </div>
          </div>

          <div>
            <div className="ca-sectlabel"><Icon name="banknote" size={13} /> Held for unpaid <span className="ca-sectlabel__count">· {fmt.money(CDB.heldTotal)} so'm</span></div>
            <div className="card">
              {CDB.held.map((o, i) => (
                <div className="led-row" key={o.id}>
                  <div className="led-row__icon down"><Icon name="receipt" size={16} /></div>
                  <div className="led-row__main">
                    <div className="led-row__t">Order #{o.id} · {o.customer.name}</div>
                    <div className="led-row__at">Assigned {o.placedAt} · unpaid</div>
                  </div>
                  <div className="led-row__amt down mono">−{fmt.money(o.total)}</div>
                </div>
              ))}
            </div>
          </div>

          <div>
            <div className="ca-sectlabel"><Icon name="history" size={13} /> Recent activity</div>
            <div className="card">
              {CDB.ledger.map((e, i) => {
                const up = e.amount >= 0;
                return (
                  <div className="led-row" key={i}>
                    <div className={"led-row__icon " + (up ? "up" : "down")}>
                      <Icon name={up ? "arrowup" : "arrowdown"} size={15} />
                    </div>
                    <div className="led-row__main">
                      <div className="led-row__t">{e.label}</div>
                      <div className="led-row__at">{e.at}</div>
                    </div>
                    <div className={"led-row__amt " + (up ? "up" : "down") + " mono"}>{fmt.signed(e.amount)}</div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

/* ----------------------------------------------------------------
   NOTIFICATIONS
---------------------------------------------------------------- */
function NotificationsScreen({ onBack, onDemo }) {
  return (
    <React.Fragment>
      <div className="det-head">
        <div className="iconbtn" onClick={onBack}><Icon name="chevleft" size={22} /></div>
        <div className="det-head__title">Notifications</div>
        <span className="ca-head__spacer"></span>
        <div className="iconbtn" onClick={onDemo} title="Demo push"><Icon name="bell" size={18} /></div>
      </div>
      <div className="ca-scroll">
        <div className="ca-pad ca-stack" style={{ paddingBottom: 40 }}>
          {CDB.notifications.map((n) => (
            <div className={"notif" + (n.unread ? " is-unread" : "")} key={n.id}>
              <div className={"notif__icon t-" + n.tone}><Icon name={n.icon} size={20} /></div>
              <div style={{ flex: 1, minWidth: 0 }}>
                <div className="notif__t">{n.title}</div>
                <div className="notif__b">{n.body}</div>
                <div className="notif__at">Today · {n.at}</div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </React.Fragment>
  );
}

/* ----------------------------------------------------------------
   PROFILE
---------------------------------------------------------------- */
function ProfileScreen({ online, setOnline, shareLoc, setShareLoc, onLogout, onDemo }) {
  const c = CDB.courier;
  return (
    <React.Fragment>
      <div className="ca-head"><div className="ca-head__row"><h1 className="ca-head__title">Profile</h1></div></div>
      <div className="ca-scroll">
        <div className="ca-pad ca-pad--tab ca-stack ca-stack--lg">
          <div className="card card__pad" style={{ display: "flex", alignItems: "center", gap: "var(--sp-4)" }}>
            <div className="avatar avatar--lg">{c.initials}</div>
            <div style={{ flex: 1 }}>
              <div style={{ fontSize: 19, fontWeight: 700, letterSpacing: "-0.02em" }}>{c.first} {c.last}</div>
              <div className="mono" style={{ color: "var(--text-secondary)", fontSize: "var(--fs-sm)" }}>{c.phone}</div>
              <div style={{ display: "flex", gap: 6, marginTop: 8 }}>
                <span className="badge t-primary">{c.id}</span>
                <span className="badge t-warning badge--dot"><Icon name="star" size={11} /> {c.rating}</span>
              </div>
            </div>
          </div>

          <div className="card">
            <InfoRow icon="scooter" tone="neutral" t="Vehicle" s={c.vehicle + " · " + c.plate} />
            <div className="divider"></div>
            <InfoRow icon="store" tone="primary" t="Branch" s={c.branch} />
          </div>

          <div>
            <div className="ca-sectlabel">Settings</div>
            <div className="card">
              <ToggleRow icon="navigation" tone="info" t="Share live location" s="Cashiers see you while on a delivery"
                         on={shareLoc} onToggle={() => setShareLoc(!shareLoc)} />
              <div className="divider"></div>
              <ToggleRow icon="power" tone="success" t="On shift" s="Receive new order assignments"
                         on={online} onToggle={() => setOnline(!online)} />
              <div className="divider"></div>
              <div className="lrow" onClick={onDemo} style={{ cursor: "pointer" }}>
                <div className="lrow__icon t-primary"><Icon name="bell" size={20} /></div>
                <div className="lrow__main"><div className="lrow__t">Test push notification</div>
                  <div className="lrow__s">Preview an incoming order alert</div></div>
                <Icon name="chevright" size={18} style={{ color: "var(--text-tertiary)" }} />
              </div>
            </div>
          </div>

          <button className="btn btn--secondary" onClick={onLogout} style={{ color: "var(--error)", borderColor: "var(--error-border)" }}>
            <Icon name="logout" size={20} /> Log out
          </button>
        </div>
      </div>
    </React.Fragment>
  );
}

function InfoRow({ icon, tone, t, s }) {
  return (
    <div className="lrow">
      <div className={"lrow__icon t-" + tone}><Icon name={icon} size={20} /></div>
      <div className="lrow__main"><div className="lrow__t">{t}</div><div className="lrow__s">{s}</div></div>
    </div>
  );
}
function ToggleRow({ icon, tone, t, s, on, onToggle }) {
  return (
    <div className="lrow" onClick={onToggle} style={{ cursor: "pointer" }}>
      <div className={"lrow__icon t-" + tone}><Icon name={icon} size={20} /></div>
      <div className="lrow__main"><div className="lrow__t">{t}</div><div className="lrow__s">{s}</div></div>
      <span className={"switch" + (on ? " is-on" : "")}></span>
    </div>
  );
}

/* ----------------------------------------------------------------
   CASH & EARNINGS  ·  shift reconciliation
---------------------------------------------------------------- */
function CashScreen({ T }) {
  const tr = T || ((k) => k);
  const r = PAY.recon;
  const [handover, setHandover] = useState(false);
  const [settled, setSettled] = useState(false);
  const [cashNow, setCashNow] = useState(r.cashInHand);
  const totalCollected = r.collectedCash + r.qrCollected;
  return (
    <React.Fragment>
      <div className="ca-head"><div className="ca-head__row">
        <h1 className="ca-head__title">{tr("cash_title")}</h1>
        <span className="ca-head__spacer"></span>
        <span className="badge t-neutral badge--dot">{tr("shift_started", { v: r.shiftStart })}</span>
      </div></div>
      <div className="ca-scroll">
        <div className="ca-pad ca-pad--tab ca-stack ca-stack--lg">

          <div className="recon-hero">
            <div className="recon-cell recon-cell--wide recon-cell--accent">
              <div className="recon-cell__l"><Icon name="banknote" size={13} /> {tr("cash_in_hand")}</div>
              <div className="recon-cell__v"><Odometer value={cashNow} /> <small>so'm</small></div>
            </div>
            <div className="recon-cell">
              <div className="recon-cell__l"><Icon name="card" size={13} /> {tr("card_qr_collected")}</div>
              <div className="recon-cell__v">{fmt.money(r.qrCollected)}</div>
            </div>
            <div className="recon-cell">
              <div className="recon-cell__l"><Icon name="wallet" size={13} /> {tr("your_payout")}</div>
              <div className="recon-cell__v">{fmt.money(r.netPayout)}</div>
            </div>
          </div>

          <div className="card">
            <div className="card__hd"><Icon name="receipt" size={15} /><span className="card__hd-title">{tr("reconciliation")}</span></div>
            <div style={{ padding: "0 var(--sp-4)" }}>
              <ReconRow l={tr("total_collected")} v={totalCollected} />
              <ReconRow l={tr("hand_in_cash")} v={r.cashInHand} strong />
              <ReconRow l={tr("net_payout")} v={r.netPayout} pos last />
            </div>
            <div className="card__pad">
              {settled ? (
                <div className="badge t-success" style={{ height: 44, width: "100%", justifyContent: "center" }}><Icon name="checkcircle" size={16} /> {tr("settled")}</div>
              ) : (
                <button className="btn btn--dark" onClick={() => setHandover(true)}>
                  <Icon name="bank" size={20} /> {tr("settle_shift")}
                </button>
              )}
              <div className="det-foot__hint" style={{ marginTop: 10 }}><Icon name="info" size={13} /> {tr("settle_note")}</div>
            </div>
          </div>

          <div>
            <div className="ca-sectlabel"><Icon name="coins" size={13} /> {tr("breakdown")}</div>
            <div className="card">
              <BreakRow icon="navigation" t={tr("fees")} v={r.deliveryFees} />
              <div className="divider"></div>
              <BreakRow icon="star" t={tr("bonuses")} v={r.bonuses} />
              <div className="divider"></div>
              <BreakRow icon="gift" t={tr("tips")} v={r.tips} />
            </div>
          </div>

          <div>
            <div className="ca-sectlabel"><Icon name="banknote" size={13} /> {tr("held_for_unpaid")} <span className="ca-sectlabel__count">· {fmt.money(CDB.heldTotal)} so'm</span></div>
            <div className="card">
              {CDB.held.map((o) => (
                <div className="led-row" key={o.id}>
                  <div className="led-row__icon down"><Icon name="receipt" size={16} /></div>
                  <div className="led-row__main">
                    <div className="led-row__t">Order #{o.id} · {o.customer.name}</div>
                    <div className="led-row__at">{o.placedAt} · {tr("unpaid")}</div>
                  </div>
                  <div className="led-row__amt down mono">−{fmt.money(o.total)}</div>
                </div>
              ))}
            </div>
          </div>

          <div>
            <div className="ca-sectlabel"><Icon name="history" size={13} /> {tr("recent_activity")}</div>
            <div className="card">
              {CDB.ledger.map((e, i) => {
                const up = e.amount >= 0;
                return (
                  <div className="led-row" key={i}>
                    <div className={"led-row__icon " + (up ? "up" : "down")}><Icon name={up ? "arrowup" : "arrowdown"} size={15} /></div>
                    <div className="led-row__main"><div className="led-row__t">{e.label}</div><div className="led-row__at">{e.at}</div></div>
                    <div className={"led-row__amt " + (up ? "up" : "down") + " mono"}>{fmt.signed(e.amount)}</div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </div>

      {handover && (
        <div className="sheet-scrim" onClick={() => setHandover(false)}>
          <div className="sheet" onClick={(e) => e.stopPropagation()}>
            <div className="sheet__grip"></div>
            <div className="sheet__title">{tr("handover_title")}</div>
            <div className="sheet__sub">{tr("handover_sub")}</div>
            <div className="ca-stack ca-stack--lg" style={{ marginTop: 4 }}>
              <div>
                <div className="ca-sectlabel" style={{ justifyContent: "center", marginBottom: 8 }}>{tr("handover_code_l")}</div>
                <div className="handover-code"><RollDigits text={r.handoverCode} /></div>
              </div>
              <div className="recon-hero">
                <div className="recon-cell"><div className="recon-cell__l">{tr("hand_in_cash")}</div><div className="recon-cell__v">{fmt.money(r.cashInHand)} <small>so'm</small></div></div>
                <div className="recon-cell"><div className="recon-cell__l">{tr("net_payout")}</div><div className="recon-cell__v">{fmt.money(r.netPayout)}</div></div>
              </div>
              <button className="btn btn--primary" onClick={() => { setSettled(true); setHandover(false); setCashNow(0); }}>
                <Icon name="check" size={20} /> {tr("confirm_settle")}
              </button>
            </div>
          </div>
        </div>
      )}
    </React.Fragment>
  );
}

function ReconRow({ l, v, strong, pos, last }) {
  return (
    <div style={{ display: "flex", alignItems: "center", padding: "11px 0", borderBottom: last ? "none" : "1px solid var(--border)" }}>
      <span style={{ color: "var(--text-secondary)", fontSize: "var(--fs-sm)", fontWeight: strong ? 700 : 500 }}>{l}</span>
      <span className="ca-head__spacer"></span>
      <span className="mono" style={{ fontWeight: 700, color: pos ? "var(--success-strong)" : "var(--text)" }}>
        {pos ? "+" : ""}{fmt.money(v)} <small style={{ color: "var(--text-tertiary)", fontFamily: "var(--font-sans)", fontWeight: 500, fontSize: 12 }}>so'm</small>
      </span>
    </div>
  );
}
function BreakRow({ icon, t, v }) {
  return (
    <div className="led-row">
      <div className="led-row__icon up"><Icon name={icon} size={15} /></div>
      <div className="led-row__main"><div className="led-row__t">{t}</div></div>
      <div className="led-row__amt up mono">+{fmt.money(v)}</div>
    </div>
  );
}

Object.assign(window, {
  LoginScreen, OrdersScreen, OrderDetail, TodayScreen, BalanceScreen, CashScreen,
  NotificationsScreen, ProfileScreen,
});
